apiVersion: v1
kind: Service
metadata:  
  name: app-service
spec:
  selector:    
    app: some-app
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30036
    protocol: TCP
