apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
spec:
  limits:
  - default:
      cpu: 300m
    defaultRequest:
      cpu: 100m
    type: Container
----
apiVersion: v1 
kind: LimitRange 
metadata:
  name: limits
  namespace: default 
spec:
  limits: 
    - min:
        memory: 250Mi
        cpu: 500m 
      max:
        memory: 2Gi
        cpu: 2 
      default:
        memory: 500Mi
        cpu: 500m 
      defaultRequest:
        memory: 250Mi
        cpu: 250m 
      maxLimitRequestRatio:
         memory: 2
         cpu: 4
      type: Container
