apiVersion: v1 
kind: Pod 
metadata:
  name: random-generator 
spec:
  containers:
  - name: random-generator
    image: k8spatterns/random-generator:1.0
    volumeMounts:
    - name: log-volume
      mountPath: "/logs"
  volumes:
  - name: log-volume 
    persistentVolumeClaim:
      claimName: random-generator-log
